project_id = "qbbvnjnpbbpskhwngsrq"

[functions.og-meta]
verify_jwt = false

[functions.send-withdrawal-email]
verify_jwt = false

[functions.send-price-update-email]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.create-booking]
verify_jwt = false
